url: "https://catcodegames.github.io"
baseurl: ""

collections:
  unitask:
    output: true
    permalink: /unity/unitask/:title/

  csharp:
    output: true
    permalink: /csharp/:title/

plugins:
  - jekyll-sitemap